### PR TITLE
Calculator component adapted so as to pass all test

### PR DESCRIPTION
**Pull request by KevChaplin**
all tests now passing
additional comments and styling for smaller screens added

### CODE REVIEW

**Comment by EndBug** [comment]
@KevChaplin Hey, sorry to bother you, but I'm having the same issue with my calculator: it works as intended, but the tests don't seem to detect the value in `#display`. How did you solve the issue?

**Comment by KevChaplin** [comment]
@EndBug,

I just had a look and if I remember correctly, I had another hook setting
the display inside a hook for calculating. This meant that in my case the
display value would be updated twice on each render. The first time it
would be old value or undefined, then correctly calculated the second time
round. The test algorithm would only read the value of display after the
first render and hence the tests were always failing. I reworked my code so
I didn't need another hook, just a plain function. To help me understand
this I did some work on trying to understand how the tests worked with a
lot of console logging. This helped me understand how my app was working
also.

If it helps, below is the forum conversation that led me in the right
direction.
https://forum.freecodecamp.org/t/javascript-calculator-help-with-tests/467578

**Comment by EndBug** [comment]
@KevChaplin Thank you so much for taking the time to look and reply!
I actually later found the same forum post: I was also using a second React hook too, after removing it the tests started to pass.
Thanks again!

**Comment by KevChaplin** [comment]
Great, glad to hear it worked out.

**Pull request merged**
